-- Doctor website Supabase schema
-- Run this in Supabase SQL Editor.

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  excerpt text,
  content text not null,
  image text,
  author text default 'Dr. Sabri Keser',
  category text,
  read_time text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.specialties (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  description text,
  icon text,
  what_is text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  title text not null,
  youtube_url text not null,
  youtube_id text not null,
  display_order integer default 0,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.blog_posts enable row level security;
alter table public.specialties enable row level security;
alter table public.videos enable row level security;

drop policy if exists "Public can read blog posts" on public.blog_posts;
drop policy if exists "Authenticated users can insert blog posts" on public.blog_posts;
drop policy if exists "Authenticated users can update blog posts" on public.blog_posts;
drop policy if exists "Authenticated users can delete blog posts" on public.blog_posts;

create policy "Public can read blog posts"
  on public.blog_posts for select
  to anon, authenticated
  using (true);

create policy "Authenticated users can insert blog posts"
  on public.blog_posts for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update blog posts"
  on public.blog_posts for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated users can delete blog posts"
  on public.blog_posts for delete
  to authenticated
  using (true);

drop policy if exists "Public can read specialties" on public.specialties;
drop policy if exists "Authenticated users can insert specialties" on public.specialties;
drop policy if exists "Authenticated users can update specialties" on public.specialties;
drop policy if exists "Authenticated users can delete specialties" on public.specialties;

create policy "Public can read specialties"
  on public.specialties for select
  to anon, authenticated
  using (true);

create policy "Authenticated users can insert specialties"
  on public.specialties for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update specialties"
  on public.specialties for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated users can delete specialties"
  on public.specialties for delete
  to authenticated
  using (true);

drop policy if exists "Public can read videos" on public.videos;
drop policy if exists "Authenticated users can insert videos" on public.videos;
drop policy if exists "Authenticated users can update videos" on public.videos;
drop policy if exists "Authenticated users can delete videos" on public.videos;

create policy "Public can read videos"
  on public.videos for select
  to anon, authenticated
  using (is_active = true);

create policy "Authenticated users can insert videos"
  on public.videos for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update videos"
  on public.videos for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated users can delete videos"
  on public.videos for delete
  to authenticated
  using (true);

create index if not exists idx_blog_posts_created_at on public.blog_posts (created_at desc);
create index if not exists idx_specialties_slug on public.specialties (slug);
create index if not exists idx_videos_display_order on public.videos (display_order);

insert into public.blog_posts (slug, title, excerpt, content, image, category, read_time)
values
  (
    'kalp-sagligini-korumak-icin-10-ipucu',
    'Kalp Sağlığını Korumak İçin 10 İpucu',
    'Kalbinizi sağlıklı tutmak ve kardiyovasküler risk faktörlerini azaltmak için temel stratejileri öğrenin.',
    '<p>Kalp sağlığı, genel sağlığınızın en önemli parçalarından biridir. Düzenli egzersiz, dengeli beslenme ve stres yönetimi kalp sağlığınızı korumanın temel taşlarıdır.</p>',
    '/medical-research-lab.png',
    'Kardiyoloji',
    '5 dakika'
  ),
  (
    'yillik-kontrollerin-onemi',
    'Yıllık Kontrollerin Önemi',
    'Düzenli sağlık taramalarının erken teşhis ve önleme için neden çok önemli olduğunu keşfedin.',
    '<p>Yıllık sağlık kontrolleri, hastalıkların erken teşhisinde hayati öneme sahiptir.</p>',
    '/doctor-medical-office.png',
    'Koruyucu Hekimlik',
    '4 dakika'
  ),
  (
    'kronik-hastaliklari-yonetmek',
    'Kronik Hastalıkları Etkili Bir Şekilde Yönetmek',
    'Doğru yönetim ve yaşam tarzı değişiklikleri ile kronik hastalıklarla iyi yaşamaya dair uzman tavsiyeleri.',
    '<p>Kronik hastalıklar doğru yönetim stratejileri ile kontrol altında tutulabilir.</p>',
    '/medical-consultation.png',
    'Kronik Hastalık',
    '6 dakika'
  )
on conflict (slug) do nothing;

insert into public.specialties (slug, title, description, icon, what_is)
values
  ('androloji', 'Androloji', 'Erkek sağlığı ve cinsel işlev', 'Stethoscope', '<h3>Androloji Nedir?</h3><p>Androloji, erkek üreme sistemi ve cinsel sağlık sorunlarının tanı ve tedavisi ile ilgilenen tıp dalıdır.</p>'),
  ('erkek-infertilitesi', 'Erkek İnfertilitesi', 'Kısırlık tanı ve tedavisi', 'Users', '<h3>Erkek İnfertilitesi Nedir?</h3><p>Erkek infertilitesi, çiftlerin çocuk sahibi olamamasında erkek faktörlerin rol oynadığı durumdur.</p>'),
  ('erektil-disfonksiyon', 'Erektil Disfonksiyon', 'Sertleşme sorunu için çözümler', 'Activity', '<h3>Erektil Disfonksiyon Nedir?</h3><p>Cinsel ilişki için yeterli ereksiyonu sağlayamama veya sürdürememe durumudur.</p>'),
  ('prematur-ejekulasyon', 'Prematür Ejekülasyon', 'Erken boşalma yönetimi', 'Activity', '<h3>Prematür Ejekülasyon Nedir?</h3><p>İstenenden daha erken boşalma durumudur.</p>'),
  ('peyronie-penis-egriligi', 'Peyronie (Penis Eğriliği)', 'Değerlendirme ve tedavi', 'Droplets', '<h3>Peyronie Hastalığı Nedir?</h3><p>Penis dokusunda plak oluşumu sonucu penisin eğrilmesi durumudur.</p>'),
  ('penil-protez-genital-estetik', 'Penil Protez & Genital Estetik', 'Mutluluk çubuğu ve estetik cerrahiler', 'Slice', '<h3>Penil Protez ve Genital Estetik Nedir?</h3><p>İlaç tedavisine yanıt vermeyen erektil disfonksiyon için protez implantasyonu.</p>'),
  ('eswt-sok-dalga', 'ESWT Şok Dalga', 'İlaçsız fonksiyon destek tedavisi', 'Waves', '<h3>ESWT Şok Dalga Tedavisi Nedir?</h3><p>Düşük yoğunluklu şok dalgaları kullanarak doku rejenerasyonunu artıran tedavi.</p>'),
  ('prp-eksozom-kok-hucre', 'PRP / Eksozom / Kök Hücre', 'Rejeneratif uygulamalar', 'Syringe', '<h3>Rejeneratif Tıp Uygulamaları Nedir?</h3><p>Vücudun kendi iyileşme mekanizmalarını kullanan tedavi yöntemleri.</p>'),
  ('kronik-prostatit', 'Kronik Prostatit', 'Neden odaklı tanı ve tedavi', 'Microscope', '<h3>Kronik Prostatit Nedir?</h3><p>Prostat bezinin uzun süreli iltihaplanması durumudur.</p>'),
  ('bph-iyi-huylu-prostat', 'BPH (İyi Huylu Prostat)', 'İlaç ve girişimsel seçenekler', 'Shield', '<h3>BPH Nedir?</h3><p>Prostat bezinin yaşla birlikte büyümesi durumudur.</p>'),
  ('tas-cerrahisi', 'Taş Cerrahisi', 'Böbrek ve üreter taşı endoürolojisi', 'TestTube', '<h3>Taş Cerrahisi Nedir?</h3><p>Böbrek, üreter ve mesane taşlarının minimal invaziv tedavisi.</p>'),
  ('pelvik-organ-sarkmasi', 'Pelvik Organ Sarkması', 'Cerrahi ve cerrahi dışı çözümler', 'Pill', '<h3>Pelvik Organ Sarkması Nedir?</h3><p>Pelvik bölge organlarının normal pozisyonlarından aşağı kayması.</p>')
on conflict (slug) do nothing;
